/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.appreactor.tecnologia.negocio;

import co.appreactor.tecnologia.modelo.entidades.Computador;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lord_Nightmare
 */
public class TablaDatos extends javax.swing.JDialog {

    private final Principal principal;

    /**
     * Creates new form TablaDatos
     *
     * @param parent
     * @param modal
     * @param principal
     */
    public TablaDatos(java.awt.Frame parent, boolean modal, Principal principal) {
        super(parent, modal);
        initComponents();
        this.principal = principal;
        generarModeloTabla(this.principal.getListaComputadores());
    }

    private Object[] generarCampos() {
        int i = 0;
        Object[] campos = new Object[9];
        campos[i++] = "Serial";
        campos[i++] = "Marca";
        campos[i++] = "Procesador";
        campos[i++] = "Disco";
        campos[i++] = "Camara";
        campos[i++] = "Cd";
        campos[i++] = "Maletin";
        campos[i++] = "Ram";
        campos[i++] = "Ruta Imagen";
        return campos;
    }

    private void generarModeloTabla(List<Computador> listaComputadores) {
        DefaultTableModel tbModel = new DefaultTableModel(null,generarCampos());
        for (Computador computador : listaComputadores) {
            tbModel.addRow(obtenerFila(computador));
        }
        tblComputadores.setModel(tbModel);
    }

    private Object[] obtenerFila(Computador computador) {
        int i = 0;
        Object[] fila = new Object[9];
        fila[i++] = computador.getSerial();
        fila[i++] = computador.getMarca();
        fila[i++] = computador.getProcesador();
        fila[i++] = computador.getDisco();
        fila[i++] = computador.isCamara()?"Sí":"No";
        fila[i++] = computador.isCd()?"Sí":"No";
        fila[i++] = computador.isMaletin()?"Sí":"No";
        fila[i++] = computador.getMemoriaRam();
        fila[i++] = computador.getRutaImagen();
        return fila;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblComputadores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblComputadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblComputadores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblComputadores;
    // End of variables declaration//GEN-END:variables
}
